export const TOKENS = {
  IUserRepo: Symbol('IUserRepo'),
  IOrgRepo: Symbol('IOrgRepo'),
  IOrgDomainRepo: Symbol('IOrgDomainRepo'),
  IOrgMembershipRepo: Symbol('IOrgMembershipRepo'),
  IInviteRepo: Symbol('IInviteRepo'),
  IAccessRequestRepo: Symbol('IAccessRequestRepo'),
  IJobRepo: Symbol('IJobRepo'),
  IJobFormRepo: Symbol('IJobFormRepo'),
  ICandidateRepo: Symbol('ICandidateRepo'),
  IBlacklistRepo: Symbol('IBlacklistRepo'),
  IApplicationRepo: Symbol('IApplicationRepo'),
  IApplicationStageHistoryRepo: Symbol('IApplicationStageHistoryRepo'),
  IInterviewRepo: Symbol('IInterviewRepo'),
  IInterviewFeedbackRepo: Symbol('IInterviewFeedbackRepo'),
  IGeneratedQuestionsRepo: Symbol('IGeneratedQuestionsRepo'),
  INoteRepo: Symbol('INoteRepo'),
  IOfferRepo: Symbol('IOfferRepo'),
  INotificationRepo: Symbol('INotificationRepo'),
  IJobAnalysisRepo: Symbol('IJobAnalysisRepo'),
  IQueueService: Symbol('IQueueService'),
  IFileService: Symbol('IFileService'),
  IMailService: Symbol('IMailService'),
  ISseService: Symbol('ISseService'),
} as const
